name: End-to-end Test for Ledger-only

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  ledger-only:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x

    defaults:
      run:
        working-directory: node

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Start up a Local ScalarDL Network
        working-directory: .github
        run: |
          git init
          git pull https://${{ github.repository_owner }}:${{ secrets.CR_PAT }}@github.com/scalar-labs/scalardl-samples.git 3.6
          docker-compose -f docker-compose.yml -f expose-cassandra-port.yml up -d cassandra
          echo -n "Wait for C* "
          until docker exec scalardl-samples-cassandra-1 cqlsh 2> /dev/null ; do
          sleep 0.5
          echo -n "#"
          done
          echo ""
          docker run --rm --network scalar-network -v "${PWD}/scalardb-schema-loader.properties":/scalardb.properties -v "${PWD}/schema.json":/schema.json ghcr.io/scalar-labs/scalardb-schema-loader:3.6.0 -c /scalardb.properties -f /schema.json
          docker-compose -f docker-compose.yml -f expose-cassandra-port.yml up scalardl-ledger-schema-loader-cassandra
          docker-compose -f docker-compose.yml -f expose-cassandra-port.yml up -d scalar-ledger ledger-envoy
          sleep 5

      - name: NPM Install
        run: npm install

      - name: NPM Test
        run: npm run e2e-client-service-binary
