name: Run `karma` to test the Web SDK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  test-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x
          - 16.x
    defaults:
      run:
        working-directory: web
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: 'https://registry.npmjs.org'

      - run: npm install

      - run: npm run build # we need to build TypeScript into JavaScript first

      - run: npm test
